schema_version = 2
id = "network"
name = "Network"
description = "Aggregate network throughput"

backend = "dist/bin/network"

[[variants]]
id = "full"
name = "Full"
width = 3
height = 2
frontend = "frontend/dist/full.js"

[[variants]]
id = "compact"
name = "Compact"
width = 1
height = 1
frontend = "frontend/dist/compact.js"
