schema_version = 2
id = "memory"
name = "RAM"
description = "RAM and swap usage"

backend = "dist/bin/memory"

[[variants]]
id = "full"
name = "Full"
width = 3
height = 2
frontend = "frontend/dist/full.js"

[[variants]]
id = "compact"
name = "Compact"
width = 1
height = 1
frontend = "frontend/dist/compact.js"

[[options]]
id = "show_swap"
name = "Show swap"
description = "Show swap usage in the detailed view"
variants = ["full"]
default = true
type = "boolean"
